In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestClassifier
data = pd.read_csv('新竹_2019.csv', encoding='big5')
data

測站                    日期                    測項                    \
0     --------------------  --------------------  --------------------   
1     新竹                           2019/1/1 0:00  AMB_TEMP               
2     新竹                           2019/1/1 0:00  CH4                    
3     新竹                           2019/1/1 0:00  CO                     
4     新竹                           2019/1/1 0:00  NMHC                   
...                    ...                   ...                   ...   
6476  新竹                         2019/12/31 0:00  THC                    
6477  新竹                         2019/12/31 0:00  WD_HR                  
6478  新竹                         2019/12/31 0:00  WIND_DIREC             
6479  新竹                         2019/12/31 0:00  WIND_SPEED             
6480  新竹                         2019/12/31 0:00  WS_HR                  

                                    0                                1  \
0     -------------------------------  -------------------------------   
1                                17.5                             17.4   
2                                1.79                             1.78   
3                                0.19                             0.21   
4                                0.04                             0.04   
...                               ...                              ...   
6476                             1.81                             1.79   
6477                               42                               41   
6478                               35                               42   
6479                              3.7                              3.5   
6480                              2.6                              2.7   

                                    2                                3  \
0     -------------------------------  -------------------------------   
1                                17.3                             17.1   
2                                 1.8                              1.8   
3                                0.22                             0.22   
4                                0.04                             0.04   
...                               ...                              ...   
6476                             1.82                             1.84   
6477                               40                               41   
6478                               36                               47   
6479                              3.4                              3.7   
6480                              2.9                              3.6   

                                    4                                5  \
0     -------------------------------  -------------------------------   
1                                16.8                             16.9   
2                                 1.8                              1.8   
3                                0.21                             0.21   
4                                0.04                             0.04   
...                               ...                              ...   
6476                             1.84                             1.85   
6477                               38                               42   
6478                               41                               35   
6479                              4.6                                5   
6480                              3.4                              3.5   

                                    6  ...                               14  \
0     -------------------------------  ...  -------------------------------   
1                                16.8  ...                               20   
2                                 1.8  ...                             1.81   
3                                0.23  ...                             0.29   
4                                0.04  ...             

In [2]:
data.drop(index = [0], axis=0, inplace=True) # row : axis = 0, column : axis = 1
data

測站                   日期                    測項                       0  \
1     新竹                          2019/1/1 0:00  AMB_TEMP              17.5   
2     新竹                          2019/1/1 0:00  CH4                   1.79   
3     新竹                          2019/1/1 0:00  CO                    0.19   
4     新竹                          2019/1/1 0:00  NMHC                  0.04   
5     新竹                          2019/1/1 0:00  NO                     0.3   
...                    ...                  ...                   ...   ...   
6476  新竹                        2019/12/31 0:00  THC                   1.81   
6477  新竹                        2019/12/31 0:00  WD_HR                   42   
6478  新竹                        2019/12/31 0:00  WIND_DIREC              35   
6479  新竹                        2019/12/31 0:00  WIND_SPEED             3.7   
6480  新竹                        2019/12/31 0:00  WS_HR                  2.6   

         1     2     3     4     5     6  ...    14    15    16    17    18  \
1     17.4  17.3  17.1  16.8  16.9  16.8  ...    20  19.5  18.7  18.1  17.9   
2     1.78   1.8   1.8   1.8   1.8   1.8  ...  1.81  1.81  1.81   1.8   1.8   
3     0.21  0.22  0.22  0.21  0.21  0.23  ...  0.29   0.3  0.31  0.31  0.31   
4     0.04  0.04  0.04  0.04  0.04  0.04  ...  0.06  0.06  0.07  0.07  0.07   
5      0.3   0.3   0.3   0.3   0.3   0.3  ...   1.1   1.2   0.7   0.6   0.5   
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   
6476  1.79  1.82  1.84  1.84  1.85  1.85  ...  1.89   1.9  1.89   1.9  1.88   
6477    41    40    41    38    42    41  ...    34    40    40    49    48   
6478    42    36    47    41    35    35  ...    26    44    46    35    50   
6479   3.5   3.4   3.7   4.6     5   4.8  ...   3.6     5   3.9   4.7   5.1   
6480   2.7   2.9   3.6   3.4   3.5   3.5  ...   3.5   3.6   3.4   3.6   3.5   

        19    20    21    22    23  
1     17.6  17.6  17.5  17.7  17.5  
2     1.81  1.81   1.8   1.8  1.79  
3      0.3  0.29  0.27  0.26  0.24  
4     0.06  0.05  0.04  0.04  0.04  
5      0.3   0.3   0.3   0.3   0.3  
...    ...   ...   ...   ...   ...  
6476  1.84  1.81  1.81  1.81   1.8  
6477    51    57    50    49    53  
6478    47    64    40    55    52  
6479   4.4   4.1   4.4   3.7   4.6  
6480   3.7   3.5   3.1   3.2   3.6  

[6480 rows x 27 columns]

In [3]:
data.head(60)

測站                   日期                    測項                       0  \
1   新竹                          2019/1/1 0:00  AMB_TEMP              17.5   
2   新竹                          2019/1/1 0:00  CH4                   1.79   
3   新竹                          2019/1/1 0:00  CO                    0.19   
4   新竹                          2019/1/1 0:00  NMHC                  0.04   
5   新竹                          2019/1/1 0:00  NO                     0.3   
6   新竹                          2019/1/1 0:00  NO2                    5.2   
7   新竹                          2019/1/1 0:00  NOx                    5.6   
8   新竹                          2019/1/1 0:00  O3                      33   
9   新竹                          2019/1/1 0:00  PM10                    19   
10  新竹                          2019/1/1 0:00  PM2.5                   13   
11  新竹                          2019/1/1 0:00  RAINFALL                 0   
12  新竹                          2019/1/1 0:00  RH                      80   
13  新竹                          2019/1/1 0:00  SO2                    1.3   
14  新竹                          2019/1/1 0:00  THC                   1.83   
15  新竹                          2019/1/1 0:00  WD_HR                   74   
16  新竹                          2019/1/1 0:00  WIND_DIREC              74   
17  新竹                          2019/1/1 0:00  WIND_SPEED             4.6   
18  新竹                          2019/1/1 0:00  WS_HR                  3.7   
19  新竹                          2019/1/2 0:00  AMB_TEMP              17.5   
20  新竹                          2019/1/2 0:00  CH4                   1.78   
21  新竹                          2019/1/2 0:00  CO                    0.23   
22  新竹                          2019/1/2 0:00  NMHC                  0.04   
23  新竹                          2019/1/2 0:00  NO                     0.3   
24  新竹                          2019/1/2 0:00  NO2                      4   
25  新竹                          2019/1/2 0:00  NOx                    4.2   
26  新竹                          2019/1/2 0:00  O3                    36.8   
27  新竹                          2019/1/2 0:00  PM10                     5   
28  新竹                          2019/1/2 0:00  PM2.5                    5   
29  新竹                          2019/1/2 0:00  RAINFALL                 0   
30  新竹                          2019/1/2 0:00  RH                      79   
31  新竹                          2019/1/2 0:00  SO2                      2   
32  新竹                          2019/1/2 0:00  THC                   1.82   
33  新竹                          2019/1/2 0:00  WD_HR                   65   
34  新竹                          2019/1/2 0:00  WIND_DIREC              68   
35  新竹                          2019/1/2 0:00  WIND_SPEED             4.2   
36  新竹                          2019/1/2 0:00  WS_HR                  3.2   
37  新竹                          2019/1/3 0:00  AMB_TEMP              18.5   
38  新竹                          2019/1/3 0:00  CH4                   1.81   
39  新竹                          2019/1/3 0:00  CO                    0.29   
40  新竹                          2019/1/3 0:00  NMHC                  0.07   
41  新竹                          2019/1/3 0:00  NO                     0.7   
42  新竹                          2019/1/3 0:00  NO2                    8.5   
43  新竹                          2019/1/3 0:00  NOx                    9.2   
44  新竹                          2019/1/3 0:00  O3                    26.7   
45  新竹                          2019/1/3 0:00  PM10                    17   
46  新竹                          2019/1/3 0:00  PM2.5                   11   
47  新竹                          2019/1/3 0:00  RAINFALL               0.2   
48  新竹                          2019/1/3 0:00  RH                      86   
49  新竹                          2019/1/3 0:00  SO2                    1.5   
50  新竹                          2019/1/3 0:00  THC                   1.88   
51  新竹                          2019/1/3 0:00  WD_HR                   71   


先處理前後空白字元

In [4]:
data.columns

Index(['測站                  ', '日期                  ', '測項                  ',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
      dtype='object')

In [5]:
data.columns = data.columns.str.strip()
data.columns

Index(['測站', '日期', '測項', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23'],
      dtype='object')

In [6]:
data.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            6471, 6472, 6473, 6474, 6475, 6476, 6477, 6478, 6479, 6480],
           dtype='int64', length=6480)

In [7]:
data.loc[59, '3']

'571.2*                         '

In [8]:
columns = ['測站', '日期', '測項', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23']
for column in columns:
    data[column] = data[column].str.strip()

In [9]:
data.loc[59, '3']

'571.2*'

取出10.11.12月資料

In [10]:
data.loc[:1, '日期']

1    2019/1/1 0:00
Name: 日期, dtype: object

In [11]:
data.loc[data['日期'] == '2019/10/1 0:00'].index

Int64Index([4825, 4826, 4827, 4828, 4829, 4830, 4831, 4832, 4833, 4834, 4835,
            4836, 4837, 4838, 4839, 4840, 4841, 4842],
           dtype='int64')

In [12]:
data = data.loc[data.loc[data['日期'] == '2019/10/1 0:00'].index[0] : , :]

In [13]:
data.head(30)

測站              日期          測項     0     1     2     3     4     5  \
4825  新竹  2019/10/1 0:00    AMB_TEMP  24.7  25.1  25.4  25.5  25.3  25.1   
4826  新竹  2019/10/1 0:00         CH4  1.66  1.66   1.7  1.71  1.72  1.71   
4827  新竹  2019/10/1 0:00          CO  0.05  0.13  0.15  0.17  0.16  0.16   
4828  新竹  2019/10/1 0:00        NMHC     0     0     0  0.02  0.02  0.01   
4829  新竹  2019/10/1 0:00          NO     0   0.3   0.3   0.3   0.3   0.3   
4830  新竹  2019/10/1 0:00         NO2   1.3   1.1   1.3   1.8   2.1   2.3   
4831  新竹  2019/10/1 0:00         NOx   1.2   1.2   1.7   2.1   2.4   2.7   
4832  新竹  2019/10/1 0:00          O3  16.7  17.3  21.9  21.5  18.8  17.5   
4833  新竹  2019/10/1 0:00        PM10    18    18    29    29    27    19   
4834  新竹  2019/10/1 0:00       PM2.5     2     4     6     9    10     7   
4835  新竹  2019/10/1 0:00    RAINFALL     0     0     0     0     0     0   
4836  新竹  2019/10/1 0:00          RH    89    87    85    84    85    86   
4837  新竹  2019/10/1 0:00         SO2   1.1   1.3   1.4   1.5   1.5   1.6   
4838  新竹  2019/10/1 0:00         THC  1.65  1.65   1.7  1.73  1.74  1.72   
4839  新竹  2019/10/1 0:00       WD_HR   292   286   291   286   268   277   
4840  新竹  2019/10/1 0:00  WIND_DIREC   283   289   276   289   250   262   
4841  新竹  2019/10/1 0:00  WIND_SPEED   2.1   1.4     2   2.5   1.8   2.4   
4842  新竹  2019/10/1 0:00       WS_HR   0.9   1.1   1.8   2.2   1.8   1.9   
4843  新竹  2019/10/2 0:00    AMB_TEMP    26  25.7  25.3  25.2  25.2    25   
4844  新竹  2019/10/2 0:00         CH4  1.95  1.94  2.18  1.99   1.9   1.9   
4845  新竹  2019/10/2 0:00          CO   0.4  0.31  0.35   0.3  0.25  0.27   
4846  新竹  2019/10/2 0:00        NMHC  0.13  0.11  0.22  0.19  0.13   0.1   
4847  新竹  2019/10/2 0:00          NO   3.8   0.9   6.9  10.3   5.8   1.2   
4848  新竹  2019/10/2 0:00         NO2  11.6  10.7  12.9  14.8  17.1  15.3   
4849  新竹  2019/10/2 0:00         NOx  15.5  11.6  19.8  25.1  22.9  16.5   
4850  新竹  2019/10/2 0:00          O3   4.3   6.2   1.6   2.1     3    12   
4851  新竹  2019/10/2 0:00        PM10    15    19    19    21    22    21   
4852  新竹  2019/10/2 0:00       PM2.5    11     9     9     9    10    12   
4853  新竹  2019/10/2 0:00    RAINFALL     0     0     0     0     0     0   
4854  新竹  2019/10/2 0:00          RH    73    74    77    77    76    77   

         6  ...     14    15    16    17    18    19    20    21    22    23  
4825  24.6  ...   32.4  31.9  30.4  29.1  28.7  28.3    28  27.4    27  26.5  
4826  1.75  ...   1.69  1.72  1.74  1.74  1.78  1.82  1.82  1.83  1.93  1.96  
4827  0.22  ...   0.27  0.32  0.36  0.39  0.49  0.57  0.58   0.6  0.69  0.49  
4828  0.03  ...   0.07   0.1  0.08  0.08  0.13  0.21  0.22  0.21  0.22  0.17  
4829   1.2  ...    1.6   1.1   0.8   0.6   0.6   0.7   0.6     2   5.1   3.8  
4830   6.1  ...    5.9   8.3  10.1   9.6  14.9  19.5  22.2  26.7    24  15.7  
4831   7.3  ...    7.4   9.4  10.8  10.3  15.5  20.2  22.8  28.6  29.1  19.5  
4832  11.8  ...     41  54.1  57.7  49.3  39.1  30.8  23.3  13.1   7.5   5.5  
4833    23  ...     17    23    47    53    47    35    33    21    22    14  
4834     4  ...      3     8    19    17    19    19    19    14    17     8  
4835     0  ...      0     0     0     0     0     0     0     0     0     0  
4836    88  ...     51    56    64    66    66    68    70    72    74    74  
4837   1.8  ...      2   2.5   3.1   2.8   3.6   3.5   4.4   3.1   2.7   2.5  
4838  1.78  ...   1.76  1.82  1.82  1.82  1.91  2.03  2.04  2.04  2.15  2.13  
4839   247  ...    241   243   249   248   251   245   128   186   176   178  
4840   239  ...    244   250   247   250   250   240    65    89   178   176  
4841     2  ...    3.3   3.6   4.9   4.4   2.8   1.7   1.2   0.5   0.9   1.1  
4842     2  ...    2.1   2.2   3.8     4   2.8   1.5   0.5   0.4   0.7   0.9  
4843  25.2  ...     31  30.3  29.6  28.9  28.4  28.4  28.5  28.2  27.9  27.6  
4844  1.96  ...   1.92  1.91  1.87  1.87  1.88  1.91  1.97  2.04   2.

NR表示無降雨，以0取代

In [14]:
data = data.replace(['NR'], [0.0])
data.head(30)

測站              日期          測項     0     1     2     3     4     5  \
4825  新竹  2019/10/1 0:00    AMB_TEMP  24.7  25.1  25.4  25.5  25.3  25.1   
4826  新竹  2019/10/1 0:00         CH4  1.66  1.66   1.7  1.71  1.72  1.71   
4827  新竹  2019/10/1 0:00          CO  0.05  0.13  0.15  0.17  0.16  0.16   
4828  新竹  2019/10/1 0:00        NMHC     0     0     0  0.02  0.02  0.01   
4829  新竹  2019/10/1 0:00          NO     0   0.3   0.3   0.3   0.3   0.3   
4830  新竹  2019/10/1 0:00         NO2   1.3   1.1   1.3   1.8   2.1   2.3   
4831  新竹  2019/10/1 0:00         NOx   1.2   1.2   1.7   2.1   2.4   2.7   
4832  新竹  2019/10/1 0:00          O3  16.7  17.3  21.9  21.5  18.8  17.5   
4833  新竹  2019/10/1 0:00        PM10    18    18    29    29    27    19   
4834  新竹  2019/10/1 0:00       PM2.5     2     4     6     9    10     7   
4835  新竹  2019/10/1 0:00    RAINFALL     0     0     0     0     0     0   
4836  新竹  2019/10/1 0:00          RH    89    87    85    84    85    86   
4837  新竹  2019/10/1 0:00         SO2   1.1   1.3   1.4   1.5   1.5   1.6   
4838  新竹  2019/10/1 0:00         THC  1.65  1.65   1.7  1.73  1.74  1.72   
4839  新竹  2019/10/1 0:00       WD_HR   292   286   291   286   268   277   
4840  新竹  2019/10/1 0:00  WIND_DIREC   283   289   276   289   250   262   
4841  新竹  2019/10/1 0:00  WIND_SPEED   2.1   1.4     2   2.5   1.8   2.4   
4842  新竹  2019/10/1 0:00       WS_HR   0.9   1.1   1.8   2.2   1.8   1.9   
4843  新竹  2019/10/2 0:00    AMB_TEMP    26  25.7  25.3  25.2  25.2    25   
4844  新竹  2019/10/2 0:00         CH4  1.95  1.94  2.18  1.99   1.9   1.9   
4845  新竹  2019/10/2 0:00          CO   0.4  0.31  0.35   0.3  0.25  0.27   
4846  新竹  2019/10/2 0:00        NMHC  0.13  0.11  0.22  0.19  0.13   0.1   
4847  新竹  2019/10/2 0:00          NO   3.8   0.9   6.9  10.3   5.8   1.2   
4848  新竹  2019/10/2 0:00         NO2  11.6  10.7  12.9  14.8  17.1  15.3   
4849  新竹  2019/10/2 0:00         NOx  15.5  11.6  19.8  25.1  22.9  16.5   
4850  新竹  2019/10/2 0:00          O3   4.3   6.2   1.6   2.1     3    12   
4851  新竹  2019/10/2 0:00        PM10    15    19    19    21    22    21   
4852  新竹  2019/10/2 0:00       PM2.5    11     9     9     9    10    12   
4853  新竹  2019/10/2 0:00    RAINFALL     0     0     0     0     0     0   
4854  新竹  2019/10/2 0:00          RH    73    74    77    77    76    77   

         6  ...     14    15    16    17    18    19    20    21    22    23  
4825  24.6  ...   32.4  31.9  30.4  29.1  28.7  28.3    28  27.4    27  26.5  
4826  1.75  ...   1.69  1.72  1.74  1.74  1.78  1.82  1.82  1.83  1.93  1.96  
4827  0.22  ...   0.27  0.32  0.36  0.39  0.49  0.57  0.58   0.6  0.69  0.49  
4828  0.03  ...   0.07   0.1  0.08  0.08  0.13  0.21  0.22  0.21  0.22  0.17  
4829   1.2  ...    1.6   1.1   0.8   0.6   0.6   0.7   0.6     2   5.1   3.8  
4830   6.1  ...    5.9   8.3  10.1   9.6  14.9  19.5  22.2  26.7    24  15.7  
4831   7.3  ...    7.4   9.4  10.8  10.3  15.5  20.2  22.8  28.6  29.1  19.5  
4832  11.8  ...     41  54.1  57.7  49.3  39.1  30.8  23.3  13.1   7.5   5.5  
4833    23  ...     17    23    47    53    47    35    33    21    22    14  
4834     4  ...      3     8    19    17    19    19    19    14    17     8  
4835     0  ...      0     0     0     0     0     0     0     0     0     0  
4836    88  ...     51    56    64    66    66    68    70    72    74    74  
4837   1.8  ...      2   2.5   3.1   2.8   3.6   3.5   4.4   3.1   2.7   2.5  
4838  1.78  ...   1.76  1.82  1.82  1.82  1.91  2.03  2.04  2.04  2.15  2.13  
4839   247  ...    241   243   249   248   251   245   128   186   176   178  
4840   239  ...    244   250   247   250   250   240    65    89   178   176  
4841     2  ...    3.3   3.6   4.9   4.4   2.8   1.7   1.2   0.5   0.9   1.1  
4842     2  ...    2.1   2.2   3.8     4   2.8   1.5   0.5   0.4   0.7   0.9  
4843  25.2  ...     31  30.3  29.6  28.9  28.4  28.4  28.5  28.2  27.9  27.6  
4844  1.96  ...   1.92  1.91  1.87  1.87  1.88  1.91  1.97  2.04   2.

看一下有怪字元的地方

In [15]:
data.loc[:4859, '10':]

10     11     12     13     14    15    16    17    18    19    20  \
4825  28.5   30.1   31.2   32.2   32.4  31.9  30.4  29.1  28.7  28.3    28   
4826  1.72    1.7   1.69    1.7   1.69  1.72  1.74  1.74  1.78  1.82  1.82   
4827  0.27   0.28   0.26   0.25   0.27  0.32  0.36  0.39  0.49  0.57  0.58   
4828  0.08   0.07   0.07   0.07   0.07   0.1  0.08  0.08  0.13  0.21  0.22   
4829   4.6    3.7    2.6    2.6    1.6   1.1   0.8   0.6   0.6   0.7   0.6   
4830   6.1    5.7    5.6    5.9    5.9   8.3  10.1   9.6  14.9  19.5  22.2   
4831  10.7    9.4    8.2    8.5    7.4   9.4  10.8  10.3  15.5  20.2  22.8   
4832  16.6   23.8   23.1   27.7     41  54.1  57.7  49.3  39.1  30.8  23.3   
4833    15     21     11     43     17    23    47    53    47    35    33   
4834     4      2      3      4      3     8    19    17    19    19    19   
4835     0      0      0      0      0     0     0     0     0     0     0   
4836    67     59     53     51     51    56    64    66    66    68    70   
4837   1.8    2.2      2    2.4      2   2.5   3.1   2.8   3.6   3.5   4.4   
4838   1.8   1.77   1.76   1.77   1.76  1.82  1.82  1.82  1.91  2.03  2.04   
4839   197    196    196    214    241   243   249   248   251   245   128   
4840   194    196    219    244    244   250   247   250   250   240    65   
4841   2.6    3.4    2.5    3.5    3.3   3.6   4.9   4.4   2.8   1.7   1.2   
4842   1.7    2.1    1.6    1.7    2.1   2.2   3.8     4   2.8   1.5   0.5   
4843  32.7   32.4   31.9   31.5     31  30.3  29.6  28.9  28.4  28.4  28.5   
4844  1.74   1.84  1.87#   1.92   1.92  1.91  1.87  1.87  1.88  1.91  1.97   
4845  0.29  0.45#   0.47   0.45   0.47  0.49  0.49  0.56   0.6  0.68  0.75   
4846  0.09   0.14  0.08#   0.08   0.07  0.07  0.09  0.12  0.11  0.13  0.17   
4847   2.3   1.5#    1.4    0.5    0.3   0.7   0.3   0.3   0.3   0.3   0.3   
4848  10.4  18.3#   15.5      7    7.4  10.7   7.8   8.5   9.6  13.4  17.2   
4849  12.7  19.8#   16.9    7.5    7.7  11.4   8.2   8.7   9.9  13.6  17.7   
4850  42.5  67.4#   85.5  108.5  104.4  89.8  84.6  79.9  75.4  64.2  52.1   
4851    25  1000#     61  1000#    114    72    69    64    69    69    76   
4852    12  1000#     43  1000#     47    46    43    46    47    47    50   
4853     0      0    0.2      0      0     0     0     0     0     0     0   
4854    52     59     63     64     68    72    76    78    80    81    80   
4855   2.3   3.5#    4.5    2.7    2.7   3.2   2.1   1.9   2.1   2.5   2.9   
4856  1.83   1.98  1.95#      2   1.99  1.98  1.96  1.99  1.99  2.04  2.14   
4857   252    263    253    260    255   262   245   251   248   171    53   
4858   246    264    249    249    247   240   228   260   279   198    50   
4859   3.4    2.9    3.4    3.4    3.4     2   1.2     2   0.7   0.5   1.5   

        21    22    23  
4825  27.4    27  26.5  
4826  1.83  1.93  1.96  
4827   0.6  0.69  0.49  
4828  0.21  0.22  0.17  
4829     2   5.1   3.8  
4830  26.7    24  15.7  
4831  28.6  29.1  19.5  
4832  13.1   7.5   5.5  
4833    21    22    14  
4834    14    17     8  
4835     0     0     0  
4836    72    74    74  
4837   3.1   2.7   2.5  
4838  2.04  2.15  2.13  
4839   186   176   178  
4840    89   178   176  
4841   0.5   0.9   1.1  
4842   0.4   0.7   0.9  
4843  28.2  27.9  27.6  
4844  2.04   2.1  2.08  
4845  0.85  0.74  0.69  
4846  0.21  0.25   0.2  
4847   0.3   0.3   0.3  
4848  27.8  21.4  19.9  
4849  28.1  21.7  20.2  
4850  28.9  35.4  27.7  
4851    82    79    74  
4852    54    55    58  
4853     0     0     0  
4854    81    82    83  
4855   3.3   5.3   3.2  
4856  2.25  2.35  2.28  
4857    51    43    55  
4858    55    53    36  
4859     1   0.9     1

In [16]:
data.columns

Index(['測站', '日期', '測項', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23'],
      dtype='object')

In [17]:
float(data.iloc[0, 13])

28.5

把怪怪的字元拿掉，用前後兩個值的平均

In [18]:
symbols = ['#', '*', 'x', 'A']
for i in range(len(data)): # row
    for j in range(3, len(data.columns)): # column
        for symbol in symbols:
            if symbol in data.iloc[i, j]:
                front_j = j - 1
                back_j = j + 1
                front_i = i
                back_i = i
                if front_j == 2: # 代表取到了測項，要往前一天的最後一小時取資料
                    front_j = len(data.columns) - 1
                    front_i = i - 18 # 前一天的 row index在前面18個
                if back_j == len(data.columns): # 代表取到超過今天的數據了
                    back_j = 3 # 隔天的第一筆數據
                    back_i = i + 18
                # 剩下的狀況就是目前有異常值，但還要繼續檢查下一個是不是異常值
                # 下一個的symbol不一定是上一個index的symbol，所以要再重測。
                # 因為我是用row by row, column by colum，所以不需要去測前面的
                while True:
                    s = 0 # 用來記錄是否都不是symbol
                    for symbol in symbols: 
                        if symbol in data.iloc[back_i, back_j]:
                            back_j += 1
                        else:
                            s += 1
                    if s == 4: # 代表4個symbol他都不在back裡面了
                        break
                # 因為可以讓中間都是異常值的數直接被平均數替代掉
                data.iloc[i, j:back_j] = str((float(data.iloc[front_i, front_j]) + float(data.iloc[back_i, back_j])) / 2)

怪字元拿掉了！！

In [19]:
data.loc[:4859, '10':]

10                  11                   12     13     14    15    16  \
4825  28.5                30.1                 31.2   32.2   32.4  31.9  30.4   
4826  1.72                 1.7                 1.69    1.7   1.69  1.72  1.74   
4827  0.27                0.28                 0.26   0.25   0.27  0.32  0.36   
4828  0.08                0.07                 0.07   0.07   0.07   0.1  0.08   
4829   4.6                 3.7                  2.6    2.6    1.6   1.1   0.8   
4830   6.1                 5.7                  5.6    5.9    5.9   8.3  10.1   
4831  10.7                 9.4                  8.2    8.5    7.4   9.4  10.8   
4832  16.6                23.8                 23.1   27.7     41  54.1  57.7   
4833    15                  21                   11     43     17    23    47   
4834     4                   2                    3      4      3     8    19   
4835     0                   0                    0      0      0     0     0   
4836    67                  59                   53     51     51    56    64   
4837   1.8                 2.2                    2    2.4      2   2.5   3.1   
4838   1.8                1.77                 1.76   1.77   1.76  1.82  1.82   
4839   197                 196                  196    214    241   243   249   
4840   194                 196                  219    244    244   250   247   
4841   2.6                 3.4                  2.5    3.5    3.3   3.6   4.9   
4842   1.7                 2.1                  1.6    1.7    2.1   2.2   3.8   
4843  32.7                32.4                 31.9   31.5     31  30.3  29.6   
4844  1.74                1.84                 1.88   1.92   1.92  1.91  1.87   
4845  0.29                0.38                 0.47   0.45   0.47  0.49  0.49   
4846  0.09                0.14  0.11000000000000001   0.08   0.07  0.07  0.09   
4847   2.3  1.8499999999999999                  1.4    0.5    0.3   0.7   0.3   
4848  10.4               12.95                 15.5      7    7.4  10.7   7.8   
4849  12.7  14.799999999999999                 16.9    7.5    7.7  11.4   8.2   
4850  42.5                64.0                 85.5  108.5  104.4  89.8  84.6   
4851    25                43.0                   61   87.5    114    72    69   
4852    12                27.5                   43   45.0     47    46    43   
4853     0                   0                  0.2      0      0     0     0   
4854    52                  59                   63     64     68    72    76   
4855   2.3                 3.4                  4.5    2.7    2.7   3.2   2.1   
4856  1.83                1.98                 1.99      2   1.99  1.98  1.96   
4857   252                 263                  253    260    255   262   245   
4858   246                 264                  249    249    247   240   228   
4859   3.4                 2.9                  3.4    3.4    3.4     2   1.2   

        17    18    19    20    21    22    23  
4825  29.1  28.7  28.3    28  27.4    27  26.5  
4826  1.74  1.78  1.82  1.82  1.83  1.93  1.96  
4827  0.39  0.49  0.57  0.58   0.6  0.69  0.49  
4828  0.08  0.13  0.21  0.22  0.21  0.22  0.17  
4829   0.6   0.6   0.7   0.6     2   5.1   3.8  
4830   9.6  14.9  19.5  22.2  26.7    24  15.7  
4831  10.3  15.5  20.2  22.8  28.6  29.1  19.5  
4832  49.3  39.1  30.8  23.3  13.1   7.5   5.5  
4833    53    47    35    33    21    22    14  
4834    17    19    19    19    14    17     8  
4835     0     0     0     0     0     0     0  
4836    66    66    68    70    72    74    74  
4837   2.8   3.6   3.5   4.4   3.1   2.7   2.5  
4838  1.82  1.91  2.03  2.04  2.04  2.15  2.13  
4839   248   251   245   128   186   176   178  
4840   250   250   240    65    89   178   176  
4841   4.4   2.8   1.7   1.2   0.5   0.9   1.1  
4842     4   2.8   1.5   0.5   0.4   0.7   0.9  
4843  28.9  28.4  28.4  28.5  28.2  27.9  27.6  
4844  1.87  1.88  1.91  1.97  2.04   2.1  2.08  
4845  0.56   0.6  0.68  0.75  0.85  0.74  0.69  
4846  0.12  0

將資料切割成訓練集(10.11月)以及測試集(12月)

In [20]:
data.loc[data['日期'] == '2019/12/31 0:00'].index[0]

6463

In [21]:
training_set = data.loc[data.loc[data['日期'] == '2019/10/1 0:00'].index[0] : 
                        data.loc[data['日期'] == '2019/12/1 0:00'].index[0] - 1, :]
training_set

測站               日期          測項     0     1     2     3     4     5  \
4825  新竹   2019/10/1 0:00    AMB_TEMP  24.7  25.1  25.4  25.5  25.3  25.1   
4826  新竹   2019/10/1 0:00         CH4  1.66  1.66   1.7  1.71  1.72  1.71   
4827  新竹   2019/10/1 0:00          CO  0.05  0.13  0.15  0.17  0.16  0.16   
4828  新竹   2019/10/1 0:00        NMHC     0     0     0  0.02  0.02  0.01   
4829  新竹   2019/10/1 0:00          NO     0   0.3   0.3   0.3   0.3   0.3   
...   ..              ...         ...   ...   ...   ...   ...   ...   ...   
5918  新竹  2019/11/30 0:00         THC  1.84  1.82  1.84  1.84  1.91  1.97   
5919  新竹  2019/11/30 0:00       WD_HR    56    65    67    66    95    96   
5920  新竹  2019/11/30 0:00  WIND_DIREC    53    70    98    20    94    83   
5921  新竹  2019/11/30 0:00  WIND_SPEED   1.7   1.7   0.8   0.7   0.9   1.3   
5922  新竹  2019/11/30 0:00       WS_HR   1.8   1.3   0.9   0.4   0.7   0.8   

         6  ...    14    15    16    17    18    19    20    21    22    23  
4825  24.6  ...  32.4  31.9  30.4  29.1  28.7  28.3    28  27.4    27  26.5  
4826  1.75  ...  1.69  1.72  1.74  1.74  1.78  1.82  1.82  1.83  1.93  1.96  
4827  0.22  ...  0.27  0.32  0.36  0.39  0.49  0.57  0.58   0.6  0.69  0.49  
4828  0.03  ...  0.07   0.1  0.08  0.08  0.13  0.21  0.22  0.21  0.22  0.17  
4829   1.2  ...   1.6   1.1   0.8   0.6   0.6   0.7   0.6     2   5.1   3.8  
...    ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
5918   1.9  ...  1.83  1.94  1.95  1.94  2.04  2.23   2.2     2  2.05  1.94  
5919    41  ...   281   271   257   246   213   165   198   162   167   168  
5920    39  ...   258   273   244   167   178   162   225   170   115   179  
5921   1.3  ...   2.1   1.7   1.3   0.8   0.9   1.2   0.8   0.9   0.9     1  
5922   0.9  ...   1.5   1.6   1.5   1.3   0.6   0.9   0.5   0.6   0.6     1  

[1098 rows x 27 columns]

In [22]:
training_set.columns

Index(['測站', '日期', '測項', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23'],
      dtype='object')

In [23]:
print(training_set.dtypes)
type(training_set)

測站    object
日期    object
測項    object
0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
22    object
23    object
dtype: object


pandas.core.frame.DataFrame

再把每小時的資料從object transfer to float，testing_set也做一樣的事

In [24]:
for column in training_set.columns[3:]:
    training_set[column] = training_set[column].astype(float)
training_set.dtypes

<ipython-input-24-a548ba7d6a1f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_set[column] = training_set[column].astype(float)


測站     object
日期     object
測項     object
0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
dtype: object

In [25]:
testing_set = data.loc[data.loc[data['日期'] == '2019/12/1 0:00'].index[0]: , :]
testing_set

測站               日期          測項     0     1     2     3     4     5  \
5923  新竹   2019/12/1 0:00    AMB_TEMP  20.5  20.1  19.9  19.8  20.1  20.1   
5924  新竹   2019/12/1 0:00         CH4  1.86  1.91  1.89  1.87  1.96  1.86   
5925  新竹   2019/12/1 0:00          CO  0.28  0.29  0.24   0.2  0.23  0.22   
5926  新竹   2019/12/1 0:00        NMHC  0.08   0.1  0.09  0.09   0.1  0.08   
5927  新竹   2019/12/1 0:00          NO   0.6   0.3   0.3   0.6   0.3  1.95   
...   ..              ...         ...   ...   ...   ...   ...   ...   ...   
6476  新竹  2019/12/31 0:00         THC  1.81  1.79  1.82  1.84  1.84  1.85   
6477  新竹  2019/12/31 0:00       WD_HR    42    41    40    41    38    42   
6478  新竹  2019/12/31 0:00  WIND_DIREC    35    42    36    47    41    35   
6479  新竹  2019/12/31 0:00  WIND_SPEED   3.7   3.5   3.4   3.7   4.6     5   
6480  新竹  2019/12/31 0:00       WS_HR   2.6   2.7   2.9   3.6   3.4   3.5   

         6  ...    14    15    16    17    18    19    20    21    22    23  
5923  19.9  ...    23  22.6  22.3    22  21.7  21.3    21    21    21  20.7  
5924  1.86  ...  1.73  1.74  1.75  1.78  1.77  1.75  1.77  1.81  1.79  1.79  
5925   0.3  ...  0.23  0.26  0.28  0.36  0.37  0.32  0.29  0.32  0.27  0.29  
5926  0.11  ...  0.04  0.05  0.07  0.12  0.12  0.08  0.09  0.12  0.09  0.09  
5927  1.95  ...   0.3   0.5   0.3   0.3   0.3   0.3   0.3   0.3   0.4   0.5  
...    ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
6476  1.85  ...  1.89   1.9  1.89   1.9  1.88  1.84  1.81  1.81  1.81   1.8  
6477    41  ...    34    40    40    49    48    51    57    50    49    53  
6478    35  ...    26    44    46    35    50    47    64    40    55    52  
6479   4.8  ...   3.6     5   3.9   4.7   5.1   4.4   4.1   4.4   3.7   4.6  
6480   3.5  ...   3.5   3.6   3.4   3.6   3.5   3.7   3.5   3.1   3.2   3.6  

[558 rows x 27 columns]

In [26]:
print(testing_set.dtypes)
print(type(testing_set))

測站    object
日期    object
測項    object
0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
22    object
23    object
dtype: object
<class 'pandas.core.frame.DataFrame'>


In [27]:
for column in testing_set.columns[3:]:
    testing_set[column] = testing_set[column].astype(float)
testing_set.dtypes

<ipython-input-27-812d28c212fa>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_set[column] = testing_set[column].astype(float)


測站     object
日期     object
測項     object
0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
dtype: object

製作時序資料: 將資料形式轉換為行(row)代表18種屬性，欄(column)代表逐時數據資料
hint: 將訓練集每18行合併，轉換成維度為(18,61*24)的DataFrame(每個屬性都有61天*24小時共1464筆資料)

In [28]:
new_training_set = training_set.iloc[:18, :]
new_training_set

測站              日期          測項       0       1       2       3       4  \
4825  新竹  2019/10/1 0:00    AMB_TEMP   24.70   25.10   25.40   25.50   25.30   
4826  新竹  2019/10/1 0:00         CH4    1.66    1.66    1.70    1.71    1.72   
4827  新竹  2019/10/1 0:00          CO    0.05    0.13    0.15    0.17    0.16   
4828  新竹  2019/10/1 0:00        NMHC    0.00    0.00    0.00    0.02    0.02   
4829  新竹  2019/10/1 0:00          NO    0.00    0.30    0.30    0.30    0.30   
4830  新竹  2019/10/1 0:00         NO2    1.30    1.10    1.30    1.80    2.10   
4831  新竹  2019/10/1 0:00         NOx    1.20    1.20    1.70    2.10    2.40   
4832  新竹  2019/10/1 0:00          O3   16.70   17.30   21.90   21.50   18.80   
4833  新竹  2019/10/1 0:00        PM10   18.00   18.00   29.00   29.00   27.00   
4834  新竹  2019/10/1 0:00       PM2.5    2.00    4.00    6.00    9.00   10.00   
4835  新竹  2019/10/1 0:00    RAINFALL    0.00    0.00    0.00    0.00    0.00   
4836  新竹  2019/10/1 0:00          RH   89.00   87.00   85.00   84.00   85.00   
4837  新竹  2019/10/1 0:00         SO2    1.10    1.30    1.40    1.50    1.50   
4838  新竹  2019/10/1 0:00         THC    1.65    1.65    1.70    1.73    1.74   
4839  新竹  2019/10/1 0:00       WD_HR  292.00  286.00  291.00  286.00  268.00   
4840  新竹  2019/10/1 0:00  WIND_DIREC  283.00  289.00  276.00  289.00  250.00   
4841  新竹  2019/10/1 0:00  WIND_SPEED    2.10    1.40    2.00    2.50    1.80   
4842  新竹  2019/10/1 0:00       WS_HR    0.90    1.10    1.80    2.20    1.80   

           5       6  ...      14      15      16      17      18      19  \
4825   25.10   24.60  ...   32.40   31.90   30.40   29.10   28.70   28.30   
4826    1.71    1.75  ...    1.69    1.72    1.74    1.74    1.78    1.82   
4827    0.16    0.22  ...    0.27    0.32    0.36    0.39    0.49    0.57   
4828    0.01    0.03  ...    0.07    0.10    0.08    0.08    0.13    0.21   
4829    0.30    1.20  ...    1.60    1.10    0.80    0.60    0.60    0.70   
4830    2.30    6.10  ...    5.90    8.30   10.10    9.60   14.90   19.50   
4831    2.70    7.30  ...    7.40    9.40   10.80   10.30   15.50   20.20   
4832   17.50   11.80  ...   41.00   54.10   57.70   49.30   39.10   30.80   
4833   19.00   23.00  ...   17.00   23.00   47.00   53.00   47.00   35.00   
4834    7.00    4.00  ...    3.00    8.00   19.00   17.00   19.00   19.00   
4835    0.00    0.00  ...    0.00    0.00    0.00    0.00    0.00    0.00   
4836   86.00   88.00  ...   51.00   56.00   64.00   66.00   66.00   68.00   
4837    1.60    1.80  ...    2.00    2.50    3.10    2.80    3.60    3.50   
4838    1.72    1.78  ...    1.76    1.82    1.82    1.82    1.91    2.03   
4839  277.00  247.00  ...  241.00  243.00  249.00  248.00  251.00  245.00   
4840  262.00  239.00  ...  244.00  250.00  247.00  250.00  250.00  240.00   
4841    2.40    2.00  ...    3.30    3.60    4.90    4.40    2.80    1.70   
4842    1.90    2.00  ...    2.10    2.20    3.80    4.00    2.80    1.50   

          20      21      22      23  
4825   28.00   27.40   27.00   26.50  
4826    1.82    1.83    1.93    1.96  
4827    0.58    0.60    0.69    0.49  
4828    0.22    0.21    0.22    0.17  
4829    0.60    2.00    5.10    3.80  
4830   22.20   26.70   24.00   15.70  
4831   22.80   28.60   29.10   19.50  
4832   23.30   13.10    7.50    5.50  
4833   33.00   21.00   22.00   14.00  
4834   19.00   14.00   17.00    8.00  
4835    0.00    0.00    0.00    0.00  
4836   70.00   72.00   74.00   74.00  
4837    4.40    3.10    2.70    2.50  
4838    2.04    2.04    2.15    2.13  
4839  128.00  186.00  176.00  178.00  
4840   65.00   89.00  178.00  176.00  
4841    1.20    0.50    0.90    1.10  
4842    0.50    0.40    0.70    0.90  

[18 rows x 27 columns]

In [29]:
# 有61筆data，i處理到 len(data) - 2 = 59就好
for i in range(int(len(training_set) / 18) - 1):
    new_training_set = pd.merge(new_training_set, training_set.iloc[(i + 1) * 18 : (i + 2) * 18, 2 : ],on='測項')
new_training_set

測站              日期          測項     0_x     1_x     2_x     3_x     4_x  \
0   新竹  2019/10/1 0:00    AMB_TEMP   24.70   25.10   25.40   25.50   25.30   
1   新竹  2019/10/1 0:00         CH4    1.66    1.66    1.70    1.71    1.72   
2   新竹  2019/10/1 0:00          CO    0.05    0.13    0.15    0.17    0.16   
3   新竹  2019/10/1 0:00        NMHC    0.00    0.00    0.00    0.02    0.02   
4   新竹  2019/10/1 0:00          NO    0.00    0.30    0.30    0.30    0.30   
5   新竹  2019/10/1 0:00         NO2    1.30    1.10    1.30    1.80    2.10   
6   新竹  2019/10/1 0:00         NOx    1.20    1.20    1.70    2.10    2.40   
7   新竹  2019/10/1 0:00          O3   16.70   17.30   21.90   21.50   18.80   
8   新竹  2019/10/1 0:00        PM10   18.00   18.00   29.00   29.00   27.00   
9   新竹  2019/10/1 0:00       PM2.5    2.00    4.00    6.00    9.00   10.00   
10  新竹  2019/10/1 0:00    RAINFALL    0.00    0.00    0.00    0.00    0.00   
11  新竹  2019/10/1 0:00          RH   89.00   87.00   85.00   84.00   85.00   
12  新竹  2019/10/1 0:00         SO2    1.10    1.30    1.40    1.50    1.50   
13  新竹  2019/10/1 0:00         THC    1.65    1.65    1.70    1.73    1.74   
14  新竹  2019/10/1 0:00       WD_HR  292.00  286.00  291.00  286.00  268.00   
15  新竹  2019/10/1 0:00  WIND_DIREC  283.00  289.00  276.00  289.00  250.00   
16  新竹  2019/10/1 0:00  WIND_SPEED    2.10    1.40    2.00    2.50    1.80   
17  新竹  2019/10/1 0:00       WS_HR    0.90    1.10    1.80    2.20    1.80   

       5_x     6_x  ...      14      15      16      17      18      19  \
0    25.10   24.60  ...   25.20   25.10   23.60   22.40   22.10   21.70   
1     1.71    1.75  ...    1.77    1.82    1.83    1.83    1.87    2.00   
2     0.16    0.22  ...    0.30    0.40    0.41    0.42    0.56    0.69   
3     0.01    0.03  ...    0.06    0.12    0.12    0.11    0.17    0.23   
4     0.30    1.20  ...    0.80    1.70    1.00    0.50    0.60    1.60   
5     2.30    6.10  ...    9.10   22.90   20.10   13.70   24.50   33.40   
6     2.70    7.30  ...    9.90   24.60   21.10   14.20   25.10   34.90   
7    17.50   11.80  ...   64.10   52.10   48.10   51.80   37.00   21.00   
8    19.00   23.00  ...   30.00   51.00   41.00   38.00   42.00   56.00   
9     7.00    4.00  ...   16.00   35.00   17.00   20.00   22.00   34.00   
10    0.00    0.00  ...    0.00    0.00    0.00    0.00    0.00    0.00   
11   86.00   88.00  ...   54.00   54.00   65.00   75.00   78.00   79.00   
12    1.60    1.80  ...    1.90    4.60    3.90    2.30    3.30    3.50   
13    1.72    1.78  ...    1.83    1.94    1.95    1.94    2.04    2.23   
14  277.00  247.00  ...  281.00  271.00  257.00  246.00  213.00  165.00   
15  262.00  239.00  ...  258.00  273.00  244.00  167.00  178.00  162.00   
16    2.40    2.00  ...    2.10    1.70    1.30    0.80    0.90    1.20   
17    1.90    2.00  ...    1.50    1.60    1.50    1.30    0.60    0.90   

        20      21      22      23  
0    21.20   21.00   20.90   20.80  
1     1.97    1.85    1.90    1.84  
2     0.71    0.48    0.50    0.34  
3     0.23    0.15    0.15    0.10  
4     2.60    1.00    1.10    0.70  
5    31.80   22.30   22.70   16.50  
6    34.40   23.20   23.70   17.20  
7    15.40   23.00   16.40   20.80  
8    56.00   51.00   41.00   47.00  
9    36.00   32.00   27.00   22.00  
10    0.00    0.00    0.00    0.00  
11   81.00   83.00   84.00   85.00  
12    3.00    3.10    2.40    2.20  
13    2.20    2.00    2.05    1.94  
14  198.00  162.00  167.00  168.00  
15  225.00  170.00  115.00  179.00  
16    0.80    0.90    0.90    1.00  
17    0.50    0.60    0.60    1.00  

[18 rows x 1467 columns]

In [30]:
new_training_set.drop(['測站', '日期'], axis=1, inplace=True)
new_training_set

測項     0_x     1_x     2_x     3_x     4_x     5_x     6_x  \
0     AMB_TEMP   24.70   25.10   25.40   25.50   25.30   25.10   24.60   
1          CH4    1.66    1.66    1.70    1.71    1.72    1.71    1.75   
2           CO    0.05    0.13    0.15    0.17    0.16    0.16    0.22   
3         NMHC    0.00    0.00    0.00    0.02    0.02    0.01    0.03   
4           NO    0.00    0.30    0.30    0.30    0.30    0.30    1.20   
5          NO2    1.30    1.10    1.30    1.80    2.10    2.30    6.10   
6          NOx    1.20    1.20    1.70    2.10    2.40    2.70    7.30   
7           O3   16.70   17.30   21.90   21.50   18.80   17.50   11.80   
8         PM10   18.00   18.00   29.00   29.00   27.00   19.00   23.00   
9        PM2.5    2.00    4.00    6.00    9.00   10.00    7.00    4.00   
10    RAINFALL    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11          RH   89.00   87.00   85.00   84.00   85.00   86.00   88.00   
12         SO2    1.10    1.30    1.40    1.50    1.50    1.60    1.80   
13         THC    1.65    1.65    1.70    1.73    1.74    1.72    1.78   
14       WD_HR  292.00  286.00  291.00  286.00  268.00  277.00  247.00   
15  WIND_DIREC  283.00  289.00  276.00  289.00  250.00  262.00  239.00   
16  WIND_SPEED    2.10    1.40    2.00    2.50    1.80    2.40    2.00   
17       WS_HR    0.90    1.10    1.80    2.20    1.80    1.90    2.00   

       7_x     8_x  ...      14      15      16      17      18      19  \
0    24.60   25.10  ...   25.20   25.10   23.60   22.40   22.10   21.70   
1     1.76    1.73  ...    1.77    1.82    1.83    1.83    1.87    2.00   
2     0.42    0.36  ...    0.30    0.40    0.41    0.42    0.56    0.69   
3     0.08    0.08  ...    0.06    0.12    0.12    0.11    0.17    0.23   
4     5.30    5.60  ...    0.80    1.70    1.00    0.50    0.60    1.60   
5     9.90    7.40  ...    9.10   22.90   20.10   13.70   24.50   33.40   
6    15.20   12.90  ...    9.90   24.60   21.10   14.20   25.10   34.90   
7     8.20   10.40  ...   64.10   52.10   48.10   51.80   37.00   21.00   
8    13.00   10.00  ...   30.00   51.00   41.00   38.00   42.00   56.00   
9     6.00    7.00  ...   16.00   35.00   17.00   20.00   22.00   34.00   
10    0.00    0.00  ...    0.00    0.00    0.00    0.00    0.00    0.00   
11   90.00   85.00  ...   54.00   54.00   65.00   75.00   78.00   79.00   
12    2.00    1.90  ...    1.90    4.60    3.90    2.30    3.30    3.50   
13    1.84    1.81  ...    1.83    1.94    1.95    1.94    2.04    2.23   
14  203.00  193.00  ...  281.00  271.00  257.00  246.00  213.00  165.00   
15  183.00  187.00  ...  258.00  273.00  244.00  167.00  178.00  162.00   
16    1.70    2.30  ...    2.10    1.70    1.30    0.80    0.90    1.20   
17    1.00    1.50  ...    1.50    1.60    1.50    1.30    0.60    0.90   

        20      21      22      23  
0    21.20   21.00   20.90   20.80  
1     1.97    1.85    1.90    1.84  
2     0.71    0.48    0.50    0.34  
3     0.23    0.15    0.15    0.10  
4     2.60    1.00    1.10    0.70  
5    31.80   22.30   22.70   16.50  
6    34.40   23.20   23.70   17.20  
7    15.40   23.00   16.40   20.80  
8    56.00   51.00   41.00   47.00  
9    36.00   32.00   27.00   22.00  
10    0.00    0.00    0.00    0.00  
11   81.00   83.00   84.00   85.00  
12    3.00    3.10    2.40    2.20  
13    2.20    2.00    2.05    1.94  
14  198.00  162.00  167.00  168.00  
15  225.00  170.00  115.00  179.00  
16    0.80    0.90    0.90    1.00  
17    0.50    0.60    0.60    1.00  

[18 rows x 1465 columns]

In [31]:
new_testing_set = testing_set.iloc[:18, :]
new_testing_set

測站              日期          測項       0       1       2       3       4  \
5923  新竹  2019/12/1 0:00    AMB_TEMP   20.50   20.10   19.90   19.80   20.10   
5924  新竹  2019/12/1 0:00         CH4    1.86    1.91    1.89    1.87    1.96   
5925  新竹  2019/12/1 0:00          CO    0.28    0.29    0.24    0.20    0.23   
5926  新竹  2019/12/1 0:00        NMHC    0.08    0.10    0.09    0.09    0.10   
5927  新竹  2019/12/1 0:00          NO    0.60    0.30    0.30    0.60    0.30   
5928  新竹  2019/12/1 0:00         NO2   13.70   11.90   11.10    8.60    8.60   
5929  新竹  2019/12/1 0:00         NOx   14.30   12.30   11.50    9.20    9.00   
5930  新竹  2019/12/1 0:00          O3   21.50   18.40   19.20   20.90   18.90   
5931  新竹  2019/12/1 0:00        PM10   41.00   41.00   39.00   37.00   41.00   
5932  新竹  2019/12/1 0:00       PM2.5   18.00   18.00   18.00   16.00   18.00   
5933  新竹  2019/12/1 0:00    RAINFALL    0.00    0.00    0.00    0.00    0.00   
5934  新竹  2019/12/1 0:00          RH   86.00   88.00   89.00   89.00   88.00   
5935  新竹  2019/12/1 0:00         SO2    2.10    1.80    2.00    1.60    1.60   
5936  新竹  2019/12/1 0:00         THC    1.94    2.01    1.98    1.96    2.06   
5937  新竹  2019/12/1 0:00       WD_HR  171.00  181.00  169.00  179.00  187.00   
5938  新竹  2019/12/1 0:00  WIND_DIREC  176.00  181.00  174.00  177.00  189.00   
5939  新竹  2019/12/1 0:00  WIND_SPEED    0.80    0.70    0.90    0.80    0.70   
5940  新竹  2019/12/1 0:00       WS_HR    0.90    0.50    0.90    0.80    0.50   

           5       6  ...      14      15     16     17     18     19     20  \
5923   20.10   19.90  ...   23.00   22.60  22.30  22.00  21.70  21.30  21.00   
5924    1.86    1.86  ...    1.73    1.74   1.75   1.78   1.77   1.75   1.77   
5925    0.22    0.30  ...    0.23    0.26   0.28   0.36   0.37   0.32   0.29   
5926    0.08    0.11  ...    0.04    0.05   0.07   0.12   0.12   0.08   0.09   
5927    1.95    1.95  ...    0.30    0.50   0.30   0.30   0.30   0.30   0.30   
5928   10.30   10.30  ...    6.00    6.10   7.80  12.00  13.10  12.40  12.70   
5929   12.30   12.30  ...    6.50    6.60   7.90  12.30  13.40  12.60  13.00   
5930   20.10   14.40  ...   61.40   61.30  55.90  47.00  45.20  43.70  38.20   
5931   39.00   38.00  ...   37.00   33.00  34.00  36.00  38.00  33.00  36.00   
5932   18.00   15.00  ...   20.00   21.00  17.00  22.00  19.00  19.00  18.00   
5933    0.00    0.00  ...    0.00    0.00   0.00   0.00   0.00   0.00   0.00   
5934   88.00   87.00  ...   75.00   75.00  75.00  76.00  76.00  79.00  81.00   
5935    1.60    1.70  ...    1.80    1.30   1.30   2.50   1.70   1.80   1.80   
5936    1.94    1.97  ...    1.77    1.79   1.82   1.90   1.89   1.83   1.86   
5937  187.00  156.00  ...  305.00  330.00  57.00  44.00  60.00  66.00  60.00   
5938  167.00   92.00  ...   51.00   42.00  24.00  52.00  69.00  60.00  62.00   
5939    0.80    0.60  ...    1.20    1.20   0.90   2.40   2.00   1.40   2.40   
5940    0.60    0.40  ...    1.10    0.10   0.50   1.70   1.40   1.20   1.50   

         21     22     23  
5923  21.00  21.00  20.70  
5924   1.81   1.79   1.79  
5925   0.32   0.27   0.29  
5926   0.12   0.09   0.09  
5927   0.30   0.40   0.50  
5928  15.70  14.35  13.00  
5929  16.10  14.80  13.50  
5930  28.10  24.60  22.00  
5931  36.00  33.00  32.00  
5932  15.00  15.00  12.00  
5933   0.00   0.00   0.00  
5934  82.00  82.00  81.00  
5935   1.80   1.40   1.30  
5936   1.93   1.88   1.88  
5937  49.00  55.00  46.00  
5938  50.00  57.00  47.00  
5939   1.90   2.80   3.80  
5940   1.60   2.10   2.20  

[18 rows x 27 columns]

In [32]:
for i in range(int(len(testing_set) / 18) - 1):
    new_testing_set = pd.merge(new_testing_set, testing_set.iloc[(i + 1) * 18 : (i + 2) * 18, 2 : ],on='測項')
new_testing_set

測站              日期          測項     0_x     1_x     2_x     3_x     4_x  \
0   新竹  2019/12/1 0:00    AMB_TEMP   20.50   20.10   19.90   19.80   20.10   
1   新竹  2019/12/1 0:00         CH4    1.86    1.91    1.89    1.87    1.96   
2   新竹  2019/12/1 0:00          CO    0.28    0.29    0.24    0.20    0.23   
3   新竹  2019/12/1 0:00        NMHC    0.08    0.10    0.09    0.09    0.10   
4   新竹  2019/12/1 0:00          NO    0.60    0.30    0.30    0.60    0.30   
5   新竹  2019/12/1 0:00         NO2   13.70   11.90   11.10    8.60    8.60   
6   新竹  2019/12/1 0:00         NOx   14.30   12.30   11.50    9.20    9.00   
7   新竹  2019/12/1 0:00          O3   21.50   18.40   19.20   20.90   18.90   
8   新竹  2019/12/1 0:00        PM10   41.00   41.00   39.00   37.00   41.00   
9   新竹  2019/12/1 0:00       PM2.5   18.00   18.00   18.00   16.00   18.00   
10  新竹  2019/12/1 0:00    RAINFALL    0.00    0.00    0.00    0.00    0.00   
11  新竹  2019/12/1 0:00          RH   86.00   88.00   89.00   89.00   88.00   
12  新竹  2019/12/1 0:00         SO2    2.10    1.80    2.00    1.60    1.60   
13  新竹  2019/12/1 0:00         THC    1.94    2.01    1.98    1.96    2.06   
14  新竹  2019/12/1 0:00       WD_HR  171.00  181.00  169.00  179.00  187.00   
15  新竹  2019/12/1 0:00  WIND_DIREC  176.00  181.00  174.00  177.00  189.00   
16  新竹  2019/12/1 0:00  WIND_SPEED    0.80    0.70    0.90    0.80    0.70   
17  新竹  2019/12/1 0:00       WS_HR    0.90    0.50    0.90    0.80    0.50   

       5_x     6_x  ...     14     15     16     17     18     19     20  \
0    20.10   19.90  ...  16.30  15.90  15.40  15.30  15.30  15.10  15.00   
1     1.86    1.86  ...   1.79   1.79   1.78   1.78   1.77   1.75   1.74   
2     0.22    0.30  ...   0.40   0.39   0.40   0.43   0.43   0.36   0.31   
3     0.08    0.11  ...   0.10   0.11   0.11   0.12   0.11   0.09   0.07   
4     1.95    1.95  ...   1.60   1.40   1.10   1.10   0.80   0.80   0.30   
5    10.30   10.30  ...   9.80  10.80  11.30  12.80  12.70  10.80   8.80   
6    12.30   12.30  ...  11.30  12.20  12.40  14.00  13.50  11.50   9.20   
7    20.10   14.40  ...  33.40  31.40  31.40  30.60  31.20  33.30  34.10   
8    39.00   38.00  ...  22.00  27.00  32.00  26.00  24.00  22.00  24.00   
9    18.00   15.00  ...  14.00  18.00  20.00  17.00  18.00  12.00  13.00   
10    0.00    0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
11   88.00   87.00  ...  73.00  74.00  76.00  74.00  73.00  72.00  73.00   
12    1.60    1.70  ...   1.00   0.50   0.50   1.00   1.20   1.40   1.40   
13    1.94    1.97  ...   1.89   1.90   1.89   1.90   1.88   1.84   1.81   
14  187.00  156.00  ...  34.00  40.00  40.00  49.00  48.00  51.00  57.00   
15  167.00   92.00  ...  26.00  44.00  46.00  35.00  50.00  47.00  64.00   
16    0.80    0.60  ...   3.60   5.00   3.90   4.70   5.10   4.40   4.10   
17    0.60    0.40  ...   3.50   3.60   3.40   3.60   3.50   3.70   3.50   

       21     22     23  
0   15.00  15.00  15.20  
1    1.74   1.74   1.74  
2    0.30   0.29   0.29  
3    0.07   0.07   0.06  
4    0.80   0.60   0.30  
5    8.60   7.80   6.90  
6    9.30   8.40   7.30  
7   34.10  34.10  33.70  
8   27.00  28.00  30.00  
9   10.00  12.00  11.00  
10   0.00   0.00   0.00  
11  72.00  72.00  73.00  
12   1.70   1.60   1.40  
13   1.81   1.81   1.80  
14  50.00  49.00  53.00  
15  40.00  55.00  52.00  
16   4.40   3.70   4.60  
17   3.10   3.20   3.60  

[18 rows x 747 columns]

In [33]:
new_testing_set.drop(['測站', '日期'], axis=1, inplace=True)
new_testing_set

測項     0_x     1_x     2_x     3_x     4_x     5_x     6_x    7_x  \
0     AMB_TEMP   20.50   20.10   19.90   19.80   20.10   20.10   19.90  19.70   
1          CH4    1.86    1.91    1.89    1.87    1.96    1.86    1.86   1.90   
2           CO    0.28    0.29    0.24    0.20    0.23    0.22    0.30   0.46   
3         NMHC    0.08    0.10    0.09    0.09    0.10    0.08    0.11   0.15   
4           NO    0.60    0.30    0.30    0.60    0.30    1.95    1.95   1.95   
5          NO2   13.70   11.90   11.10    8.60    8.60   10.30   10.30  10.30   
6          NOx   14.30   12.30   11.50    9.20    9.00   12.30   12.30  12.30   
7           O3   21.50   18.40   19.20   20.90   18.90   20.10   14.40   9.00   
8         PM10   41.00   41.00   39.00   37.00   41.00   39.00   38.00  38.00   
9        PM2.5   18.00   18.00   18.00   16.00   18.00   18.00   15.00  26.00   
10    RAINFALL    0.00    0.00    0.00    0.00    0.00    0.00    0.00   0.00   
11          RH   86.00   88.00   89.00   89.00   88.00   88.00   87.00  84.00   
12         SO2    2.10    1.80    2.00    1.60    1.60    1.60    1.70   1.80   
13         THC    1.94    2.01    1.98    1.96    2.06    1.94    1.97   2.05   
14       WD_HR  171.00  181.00  169.00  179.00  187.00  187.00  156.00  54.00   
15  WIND_DIREC  176.00  181.00  174.00  177.00  189.00  167.00   92.00  35.00   
16  WIND_SPEED    0.80    0.70    0.90    0.80    0.70    0.80    0.60   0.80   
17       WS_HR    0.90    0.50    0.90    0.80    0.50    0.60    0.40   0.70   

      8_x  ...     14     15     16     17     18     19     20     21     22  \
0   20.80  ...  16.30  15.90  15.40  15.30  15.30  15.10  15.00  15.00  15.00   
1    1.81  ...   1.79   1.79   1.78   1.78   1.77   1.75   1.74   1.74   1.74   
2    0.39  ...   0.40   0.39   0.40   0.43   0.43   0.36   0.31   0.30   0.29   
3    0.12  ...   0.10   0.11   0.11   0.12   0.11   0.09   0.07   0.07   0.07   
4    1.95  ...   1.60   1.40   1.10   1.10   0.80   0.80   0.30   0.80   0.60   
5   10.30  ...   9.80  10.80  11.30  12.80  12.70  10.80   8.80   8.60   7.80   
6   12.30  ...  11.30  12.20  12.40  14.00  13.50  11.50   9.20   9.30   8.40   
7   16.60  ...  33.40  31.40  31.40  30.60  31.20  33.30  34.10  34.10  34.10   
8   41.00  ...  22.00  27.00  32.00  26.00  24.00  22.00  24.00  27.00  28.00   
9   21.00  ...  14.00  18.00  20.00  17.00  18.00  12.00  13.00  10.00  12.00   
10   0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
11  78.00  ...  73.00  74.00  76.00  74.00  73.00  72.00  73.00  72.00  72.00   
12   2.00  ...   1.00   0.50   0.50   1.00   1.20   1.40   1.40   1.70   1.60   
13   1.93  ...   1.89   1.90   1.89   1.90   1.88   1.84   1.81   1.81   1.81   
14  49.00  ...  34.00  40.00  40.00  49.00  48.00  51.00  57.00  50.00  49.00   
15  67.00  ...  26.00  44.00  46.00  35.00  50.00  47.00  64.00  40.00  55.00   
16   1.00  ...   3.60   5.00   3.90   4.70   5.10   4.40   4.10   4.40   3.70   
17   0.90  ...   3.50   3.60   3.40   3.60   3.50   3.70   3.50   3.10   3.20   

       23  
0   15.20  
1    1.74  
2    0.29  
3    0.06  
4    0.30  
5    6.90  
6    7.30  
7   33.70  
8   30.00  
9   11.00  
10   0.00  
11  73.00  
12   1.40  
13   1.80  
14  53.00  
15  52.00  
16   4.60  
17   3.60  

[18 rows x 745 columns]

將未來第一個小時當預測目標，
X只有PM2.5 (e.g. X[0]會有6個特徵，即第0~5小時的PM2.5數值)，
這裡整理training_set的x, y 資料

In [34]:
new_training_set.loc[new_training_set['測項'] == 'PM2.5'].index[0]

9

In [35]:
training_x = new_training_set.iloc[new_training_set.loc[new_training_set['測項'] == 'PM2.5'].index[0], 1:]
print(training_x)
print(training_x.shape)
print(len(training_x))

0_x     2
1_x     4
2_x     6
3_x     9
4_x    10
       ..
19     34
20     36
21     32
22     27
23     22
Name: 9, Length: 1464, dtype: object
(1464,)
1464


In [36]:
training_x_np = np.zeros((len(training_x) - 6, 6))
print(training_x_np)
print(training_x_np.shape[0])

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
1458


In [37]:
def get_PM25_data_x_from(data_df, data_np, amount_in_group): 
    # data_df : 原本的資料
    # data_np : 我要存的格式
    # amount_in_group : 幾個資料一組
    for i in range(len(data_df) - amount_in_group):
        k = i
        for j in range(6):
            data_np[i][j] = data_df.iloc[k, ]
            k += 1
    return data_np
training_x_np = get_PM25_data_x_from(training_x, training_x_np, 6)
print(training_x_np)
print(training_x_np[1450 : ])

[[ 2.  4.  6.  9. 10.  7.]
 [ 4.  6.  9. 10.  7.  4.]
 [ 6.  9. 10.  7.  4.  6.]
 ...
 [35. 17. 20. 22. 34. 36.]
 [17. 20. 22. 34. 36. 32.]
 [20. 22. 34. 36. 32. 27.]]
[[ 8. 14. 18. 15. 16. 35.]
 [14. 18. 15. 16. 35. 17.]
 [18. 15. 16. 35. 17. 20.]
 [15. 16. 35. 17. 20. 22.]
 [16. 35. 17. 20. 22. 34.]
 [35. 17. 20. 22. 34. 36.]
 [17. 20. 22. 34. 36. 32.]
 [20. 22. 34. 36. 32. 27.]]


In [38]:
training_y_np = np.zeros(len(training_x_np))
def get_PM25_data_y_from(data_df, data_np, amount_in_group):
    for i in range(len(data_df) - amount_in_group):
        data_np[i] = data_df.iloc[i + amount_in_group,]
    return data_np
training_y_np = get_PM25_data_y_from(training_x, training_y_np, 6)
print(training_y_np)
print(len(training_y_np))

[ 4.  6.  7. ... 32. 27. 22.]
1458


這裡整理testing_set的x, y 資料

In [39]:
testing_x = new_testing_set.iloc[new_testing_set.loc[new_testing_set['測項'] == 'PM2.5'].index[0], 1:]
testing_x_np = np.zeros((len(testing_x) - 6, 6))
testing_x_np = get_PM25_data_x_from(testing_x, testing_x_np, 6)
print(testing_x_np)
print(len(testing_x_np))

[[18. 18. 18. 16. 18. 18.]
 [18. 18. 16. 18. 18. 15.]
 [18. 16. 18. 18. 15. 26.]
 ...
 [18. 20. 17. 18. 12. 13.]
 [20. 17. 18. 12. 13. 10.]
 [17. 18. 12. 13. 10. 12.]]
738


In [40]:
testing_y_np = np.zeros(len(testing_x_np))
testing_y_np = get_PM25_data_y_from(testing_x, testing_y_np, 6)
print(testing_y_np)
print(len(testing_y_np))

[15.  26.  21.  23.  19.  23.  21.  17.  20.  21.  17.  22.  19.  19.
 18.  15.  15.  12.  14.  11.  12.  14.  13.  14.  15.  11.  10.  11.
 12.  11.  10.  10.  17.  16.  27.  27.  26.  25.  31.  26.  20.  15.
 17.  17.  19.  20.  18.  19.  22.  16.  17.  14.  16.5 19.  14.  11.
 16.  18.  15.  16.  17.  15.  14.  14.  17.  16.  12.  13.   9.  12.
 12.   9.   6.   7.   8.  11.   9.   9.  10.  10.  10.  15.  17.  19.
 18.  20.  16.  17.  13.  11.  15.  14.  13.  12.  13.  16.  11.  11.
 10.  10.  10.  10.   7.   8.  11.   6.   7.   8.   6.   5.  11.   7.
  7.   6.   7.   7.   4.   5.   7.   7.   6.   5.   4.   3.   2.   1.
  2.   4.   2.   1.   5.   4.   3.   5.   5.   1.   1.   2.   3.   1.
  1.   1.   4.   3.   2.   3.   4.   4.   5.   8.  10.  12.  11.  10.
 11.   7.   6.   8.  10.   7.   8.   8.   7.   8.   5.   4.   7.   6.
  5.   8.   5.   4.   4.   7.   7.   6.   6.  10.   9.  15.  15.  12.
 11.  12.  14.  11.  15.  12.  12.  15.  11.  16.  12.  16.  17.  13.
 11.  11.  11.   9. 

做Linear Regression

'''
The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse).
A constant model that always predicts the expected value of y, 
disregarding the input features, would get a R^2 score of 0.0.
'''

In [41]:
def linear_regression(training_set_x, training_set_y, testing_set_x, testing_set_y):    
    x, y = training_set_x, training_set_y
    reg = LinearRegression().fit(x, y)
    predict_y = reg.predict(testing_set_x)
    y_true = testing_set_y
    y_pred = predict_y
    return mean_absolute_error(y_true, y_pred)

'''
用於評估預測結果和真實資料集的接近程度的程度，其其值越小說明擬合效果越好。
MAE output is non-negative floating point. The best value is 0.0.
'''

In [42]:
linear_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

2.6136558911044343

做Random Forest Regression

In [43]:
def random_forest_regression(training_set_x, training_set_y, testing_set_x, testing_set_y):    
    clf = RandomForestClassifier(max_depth=10, random_state=1)
    x, y = training_set_x, training_set_y
    y = np.array(y, dtype=int)
    clf.fit(x, y)
    predict_y = clf.predict(testing_set_x)
    y_true = testing_set_y
    y_pred = predict_y
    return mean_absolute_error(y_true, y_pred)

In [44]:
random_forest_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

3.285230352303523

將未來第六個小時當預測目標
X只有PM2.5 (e.g. X[0]會有6個特徵，即第0~5小時的PM2.5數值)
這裡整理training_set的x, y 資料

In [45]:
training_x_np = np.zeros((len(training_x) - 11, 6))
print(len(training_x_np))
training_x_np = get_PM25_data_x_from(training_x, training_x_np, 11)
print(training_x_np)

1453
[[ 2.  4.  6.  9. 10.  7.]
 [ 4.  6.  9. 10.  7.  4.]
 [ 6.  9. 10.  7.  4.  6.]
 ...
 [ 8. 14. 18. 15. 16. 35.]
 [14. 18. 15. 16. 35. 17.]
 [18. 15. 16. 35. 17. 20.]]


In [46]:
training_y_np = np.zeros(len(training_x_np))
training_y_np = get_PM25_data_y_from(training_x, training_y_np, 11)
print(training_y_np)

[ 2.  3.  4. ... 32. 27. 22.]


這裡整理testing_set的x, y 資料

In [47]:
testing_x = new_testing_set.iloc[new_testing_set.loc[new_testing_set['測項'] == 'PM2.5'].index[0], 1:]
testing_x_np = np.zeros((len(testing_x) - 11, 6))
testing_x_np = get_PM25_data_x_from(testing_x, testing_x_np, 11)
print(testing_x_np)
print(len(testing_x_np))

[[18. 18. 18. 16. 18. 18.]
 [18. 18. 16. 18. 18. 15.]
 [18. 16. 18. 18. 15. 26.]
 ...
 [ 7. 10. 11. 16. 14. 18.]
 [10. 11. 16. 14. 18. 20.]
 [11. 16. 14. 18. 20. 17.]]
733


In [48]:
testing_y_np = np.zeros(len(testing_x_np))
testing_y_np = get_PM25_data_y_from(testing_x, testing_y_np, 11)
print(testing_y_np)
print(len(testing_y_np))

[23.  21.  17.  20.  21.  17.  22.  19.  19.  18.  15.  15.  12.  14.
 11.  12.  14.  13.  14.  15.  11.  10.  11.  12.  11.  10.  10.  17.
 16.  27.  27.  26.  25.  31.  26.  20.  15.  17.  17.  19.  20.  18.
 19.  22.  16.  17.  14.  16.5 19.  14.  11.  16.  18.  15.  16.  17.
 15.  14.  14.  17.  16.  12.  13.   9.  12.  12.   9.   6.   7.   8.
 11.   9.   9.  10.  10.  10.  15.  17.  19.  18.  20.  16.  17.  13.
 11.  15.  14.  13.  12.  13.  16.  11.  11.  10.  10.  10.  10.   7.
  8.  11.   6.   7.   8.   6.   5.  11.   7.   7.   6.   7.   7.   4.
  5.   7.   7.   6.   5.   4.   3.   2.   1.   2.   4.   2.   1.   5.
  4.   3.   5.   5.   1.   1.   2.   3.   1.   1.   1.   4.   3.   2.
  3.   4.   4.   5.   8.  10.  12.  11.  10.  11.   7.   6.   8.  10.
  7.   8.   8.   7.   8.   5.   4.   7.   6.   5.   8.   5.   4.   4.
  7.   7.   6.   6.  10.   9.  15.  15.  12.  11.  12.  14.  11.  15.
 12.  12.  15.  11.  16.  12.  16.  17.  13.  11.  11.  11.   9.  12.
 16.  19.  21.  19. 

做Linear Regression

In [49]:
linear_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

4.839609070011748

做Random Forest Regression

In [50]:
random_forest_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

5.560027285129604

將未來第一個小時當預測目標，
x取所有18種屬性 (e.g. X[0]會有18*6個特徵，即第0~5小時的所有18種屬性數值)，
先處理training set的x, y

In [51]:
training_x = new_training_set.iloc[:, 1:]
training_x

0_x     1_x     2_x     3_x     4_x     5_x     6_x     7_x     8_x  \
0    24.70   25.10   25.40   25.50   25.30   25.10   24.60   24.60   25.10   
1     1.66    1.66    1.70    1.71    1.72    1.71    1.75    1.76    1.73   
2     0.05    0.13    0.15    0.17    0.16    0.16    0.22    0.42    0.36   
3     0.00    0.00    0.00    0.02    0.02    0.01    0.03    0.08    0.08   
4     0.00    0.30    0.30    0.30    0.30    0.30    1.20    5.30    5.60   
5     1.30    1.10    1.30    1.80    2.10    2.30    6.10    9.90    7.40   
6     1.20    1.20    1.70    2.10    2.40    2.70    7.30   15.20   12.90   
7    16.70   17.30   21.90   21.50   18.80   17.50   11.80    8.20   10.40   
8    18.00   18.00   29.00   29.00   27.00   19.00   23.00   13.00   10.00   
9     2.00    4.00    6.00    9.00   10.00    7.00    4.00    6.00    7.00   
10    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11   89.00   87.00   85.00   84.00   85.00   86.00   88.00   90.00   85.00   
12    1.10    1.30    1.40    1.50    1.50    1.60    1.80    2.00    1.90   
13    1.65    1.65    1.70    1.73    1.74    1.72    1.78    1.84    1.81   
14  292.00  286.00  291.00  286.00  268.00  277.00  247.00  203.00  193.00   
15  283.00  289.00  276.00  289.00  250.00  262.00  239.00  183.00  187.00   
16    2.10    1.40    2.00    2.50    1.80    2.40    2.00    1.70    2.30   
17    0.90    1.10    1.80    2.20    1.80    1.90    2.00    1.00    1.50   

       9_x  ...      14      15      16      17      18      19      20  \
0    26.80  ...   25.20   25.10   23.60   22.40   22.10   21.70   21.20   
1     1.73  ...    1.77    1.82    1.83    1.83    1.87    2.00    1.97   
2     0.29  ...    0.30    0.40    0.41    0.42    0.56    0.69    0.71   
3     0.08  ...    0.06    0.12    0.12    0.11    0.17    0.23    0.23   
4     4.80  ...    0.80    1.70    1.00    0.50    0.60    1.60    2.60   
5     6.00  ...    9.10   22.90   20.10   13.70   24.50   33.40   31.80   
6    10.80  ...    9.90   24.60   21.10   14.20   25.10   34.90   34.40   
7    13.20  ...   64.10   52.10   48.10   51.80   37.00   21.00   15.40   
8    13.00  ...   30.00   51.00   41.00   38.00   42.00   56.00   56.00   
9     6.00  ...   16.00   35.00   17.00   20.00   22.00   34.00   36.00   
10    0.00  ...    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11   75.00  ...   54.00   54.00   65.00   75.00   78.00   79.00   81.00   
12    1.90  ...    1.90    4.60    3.90    2.30    3.30    3.50    3.00   
13    1.81  ...    1.83    1.94    1.95    1.94    2.04    2.23    2.20   
14  200.00  ...  281.00  271.00  257.00  246.00  213.00  165.00  198.00   
15  196.00  ...  258.00  273.00  244.00  167.00  178.00  162.00  225.00   
16    2.80  ...    2.10    1.70    1.30    0.80    0.90    1.20    0.80   
17    2.00  ...    1.50    1.60    1.50    1.30    0.60    0.90    0.50   

        21      22      23  
0    21.00   20.90   20.80  
1     1.85    1.90    1.84  
2     0.48    0.50    0.34  
3     0.15    0.15    0.10  
4     1.00    1.10    0.70  
5    22.30   22.70   16.50  
6    23.20   23.70   17.20  
7    23.00   16.40   20.80  
8    51.00   41.00   47.00  
9    32.00   27.00   22.00  
10    0.00    0.00    0.00  
11   83.00   84.00   85.00  
12    3.10    2.40    2.20  
13    2.00    2.05    1.94  
14  162.00  167.00  168.00  
15  170.00  115.00  179.00  
16    0.90    0.90    1.00  
17    0.60    0.60    1.00  

[18 rows x 1464 columns]

In [52]:
print(training_x.shape[1])

1464


In [53]:
training_x_np = np.zeros((training_x.shape[1] - 6, 18 * 6))
print(len(training_x_np))
print(training_x_np.shape)

1458
(1458, 108)


In [54]:
def get_PM25_Alldata_x_from(data_df, data_np, amount_in_group): 
    # data_df : 原本的資料
    # data_np : 我要存的格式
    # amount_in_group : 幾個資料一組
    for i in range(data_df.shape[1] - amount_in_group):
        count = 0
        for j in range(18):
            k = i
            for k in range(i, i + 6):
                data_np[i][count] = data_df.iloc[j, k]
                count += 1
                k += 1
    return data_np
training_x_np = get_PM25_Alldata_x_from(training_x, training_x_np, 6)
print(training_x_np)

[[24.7 25.1 25.4 ...  2.2  1.8  1.9]
 [25.1 25.4 25.5 ...  1.8  1.9  2. ]
 [25.4 25.5 25.3 ...  1.9  2.   1. ]
 ...
 [25.1 23.6 22.4 ...  0.6  0.9  0.5]
 [23.6 22.4 22.1 ...  0.9  0.5  0.6]
 [22.4 22.1 21.7 ...  0.5  0.6  0.6]]


In [55]:
training_y_np = np.zeros(len(training_x_np))
def get_PM25_Alldata_y_from(data_df, data_np, amount_in_group):
    for i in range(len(data_np)):
        data_np[i] = data_df.iloc[9, i + 6]
    return data_np
training_y_np = get_PM25_Alldata_y_from(training_x, training_y_np, 6)
print(training_y_np)

[ 4.  6.  7. ... 32. 27. 22.]


再處理testing set的x, y

In [56]:
testing_x = new_testing_set.iloc[:, 1:]
testing_x_np = np.zeros((testing_x.shape[1] - 6, 18 * 6))
testing_x_np = get_PM25_Alldata_x_from(testing_x, testing_x_np, 6)
print(testing_x_np)
print(len(testing_x_np))

[[20.5 20.1 19.9 ...  0.8  0.5  0.6]
 [20.1 19.9 19.8 ...  0.5  0.6  0.4]
 [19.9 19.8 20.1 ...  0.6  0.4  0.7]
 ...
 [15.9 15.4 15.3 ...  3.5  3.7  3.5]
 [15.4 15.3 15.3 ...  3.7  3.5  3.1]
 [15.3 15.3 15.1 ...  3.5  3.1  3.2]]
738


In [57]:
testing_y_np = np.zeros(len(testing_x_np))
print(len(testing_y_np))
testing_y_np = get_PM25_Alldata_y_from(testing_x, testing_y_np, 6)
print(testing_y_np)

738
[15.  26.  21.  23.  19.  23.  21.  17.  20.  21.  17.  22.  19.  19.
 18.  15.  15.  12.  14.  11.  12.  14.  13.  14.  15.  11.  10.  11.
 12.  11.  10.  10.  17.  16.  27.  27.  26.  25.  31.  26.  20.  15.
 17.  17.  19.  20.  18.  19.  22.  16.  17.  14.  16.5 19.  14.  11.
 16.  18.  15.  16.  17.  15.  14.  14.  17.  16.  12.  13.   9.  12.
 12.   9.   6.   7.   8.  11.   9.   9.  10.  10.  10.  15.  17.  19.
 18.  20.  16.  17.  13.  11.  15.  14.  13.  12.  13.  16.  11.  11.
 10.  10.  10.  10.   7.   8.  11.   6.   7.   8.   6.   5.  11.   7.
  7.   6.   7.   7.   4.   5.   7.   7.   6.   5.   4.   3.   2.   1.
  2.   4.   2.   1.   5.   4.   3.   5.   5.   1.   1.   2.   3.   1.
  1.   1.   4.   3.   2.   3.   4.   4.   5.   8.  10.  12.  11.  10.
 11.   7.   6.   8.  10.   7.   8.   8.   7.   8.   5.   4.   7.   6.
  5.   8.   5.   4.   4.   7.   7.   6.   6.  10.   9.  15.  15.  12.
 11.  12.  14.  11.  15.  12.  12.  15.  11.  16.  12.  16.  17.  13.
 11.  11.  11.  

用Linear Regression

In [58]:
linear_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

3.7329306223569962

做Random Forest Regression

In [59]:
random_forest_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

3.5657181571815717

將未來第六個小時當預測目標
X有所有18種屬性 (e.g. X[0]會有18*6個特徵，即第0~5小時的所有18種屬性數值)
這裡整理training_set的x, y 資料

In [60]:
training_x = new_training_set.iloc[:, 1:]
training_x

0_x     1_x     2_x     3_x     4_x     5_x     6_x     7_x     8_x  \
0    24.70   25.10   25.40   25.50   25.30   25.10   24.60   24.60   25.10   
1     1.66    1.66    1.70    1.71    1.72    1.71    1.75    1.76    1.73   
2     0.05    0.13    0.15    0.17    0.16    0.16    0.22    0.42    0.36   
3     0.00    0.00    0.00    0.02    0.02    0.01    0.03    0.08    0.08   
4     0.00    0.30    0.30    0.30    0.30    0.30    1.20    5.30    5.60   
5     1.30    1.10    1.30    1.80    2.10    2.30    6.10    9.90    7.40   
6     1.20    1.20    1.70    2.10    2.40    2.70    7.30   15.20   12.90   
7    16.70   17.30   21.90   21.50   18.80   17.50   11.80    8.20   10.40   
8    18.00   18.00   29.00   29.00   27.00   19.00   23.00   13.00   10.00   
9     2.00    4.00    6.00    9.00   10.00    7.00    4.00    6.00    7.00   
10    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11   89.00   87.00   85.00   84.00   85.00   86.00   88.00   90.00   85.00   
12    1.10    1.30    1.40    1.50    1.50    1.60    1.80    2.00    1.90   
13    1.65    1.65    1.70    1.73    1.74    1.72    1.78    1.84    1.81   
14  292.00  286.00  291.00  286.00  268.00  277.00  247.00  203.00  193.00   
15  283.00  289.00  276.00  289.00  250.00  262.00  239.00  183.00  187.00   
16    2.10    1.40    2.00    2.50    1.80    2.40    2.00    1.70    2.30   
17    0.90    1.10    1.80    2.20    1.80    1.90    2.00    1.00    1.50   

       9_x  ...      14      15      16      17      18      19      20  \
0    26.80  ...   25.20   25.10   23.60   22.40   22.10   21.70   21.20   
1     1.73  ...    1.77    1.82    1.83    1.83    1.87    2.00    1.97   
2     0.29  ...    0.30    0.40    0.41    0.42    0.56    0.69    0.71   
3     0.08  ...    0.06    0.12    0.12    0.11    0.17    0.23    0.23   
4     4.80  ...    0.80    1.70    1.00    0.50    0.60    1.60    2.60   
5     6.00  ...    9.10   22.90   20.10   13.70   24.50   33.40   31.80   
6    10.80  ...    9.90   24.60   21.10   14.20   25.10   34.90   34.40   
7    13.20  ...   64.10   52.10   48.10   51.80   37.00   21.00   15.40   
8    13.00  ...   30.00   51.00   41.00   38.00   42.00   56.00   56.00   
9     6.00  ...   16.00   35.00   17.00   20.00   22.00   34.00   36.00   
10    0.00  ...    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
11   75.00  ...   54.00   54.00   65.00   75.00   78.00   79.00   81.00   
12    1.90  ...    1.90    4.60    3.90    2.30    3.30    3.50    3.00   
13    1.81  ...    1.83    1.94    1.95    1.94    2.04    2.23    2.20   
14  200.00  ...  281.00  271.00  257.00  246.00  213.00  165.00  198.00   
15  196.00  ...  258.00  273.00  244.00  167.00  178.00  162.00  225.00   
16    2.80  ...    2.10    1.70    1.30    0.80    0.90    1.20    0.80   
17    2.00  ...    1.50    1.60    1.50    1.30    0.60    0.90    0.50   

        21      22      23  
0    21.00   20.90   20.80  
1     1.85    1.90    1.84  
2     0.48    0.50    0.34  
3     0.15    0.15    0.10  
4     1.00    1.10    0.70  
5    22.30   22.70   16.50  
6    23.20   23.70   17.20  
7    23.00   16.40   20.80  
8    51.00   41.00   47.00  
9    32.00   27.00   22.00  
10    0.00    0.00    0.00  
11   83.00   84.00   85.00  
12    3.10    2.40    2.20  
13    2.00    2.05    1.94  
14  162.00  167.00  168.00  
15  170.00  115.00  179.00  
16    0.90    0.90    1.00  
17    0.60    0.60    1.00  

[18 rows x 1464 columns]

In [61]:
training_x_np = np.zeros((training_x.shape[1] - 11, 18 * 6))
training_x_np = get_PM25_Alldata_x_from(training_x, training_x_np, 11)
print(training_x_np)
print(len(training_x_np))

[[24.7 25.1 25.4 ...  2.2  1.8  1.9]
 [25.1 25.4 25.5 ...  1.8  1.9  2. ]
 [25.4 25.5 25.3 ...  1.9  2.   1. ]
 ...
 [23.7 24.9 25.1 ...  1.7  1.5  1.6]
 [24.9 25.1 25.1 ...  1.5  1.6  1.5]
 [25.1 25.1 25.2 ...  1.6  1.5  1.3]]
1453


In [62]:
training_y_np = np.zeros(len(training_x_np))
training_y_np = get_PM25_Alldata_y_from(training_x, training_y_np, 11)
print(training_y_np)
print(len(training_y_np))

[ 4.  6.  7. ... 17. 20. 22.]
1453


再處理testing set的x, y

In [63]:
testing_x = new_testing_set.iloc[:, 1:]
testing_x_np = np.zeros((testing_x.shape[1] - 11, 18 * 6))
testing_x_np = get_PM25_Alldata_x_from(testing_x, testing_x_np, 11)
print(testing_x_np)
print(len(testing_x_np))

[[20.5 20.1 19.9 ...  0.8  0.5  0.6]
 [20.1 19.9 19.8 ...  0.5  0.6  0.4]
 [19.9 19.8 20.1 ...  0.6  0.4  0.7]
 ...
 [16.2 16.8 16.9 ...  3.8  3.5  3.6]
 [16.8 16.9 17.1 ...  3.5  3.6  3.4]
 [16.9 17.1 16.3 ...  3.6  3.4  3.6]]
733


In [64]:
testing_y_np = np.zeros(len(testing_x_np))
testing_y_np = get_PM25_Alldata_y_from(testing_x, testing_y_np, 11) 
print(training_y_np)

[ 4.  6.  7. ... 17. 20. 22.]


用Linear Regression

In [65]:
linear_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

3.7604398413161895

做Random Forest Regression

In [66]:
random_forest_regression(training_x_np, training_y_np,testing_x_np, testing_y_np)

3.690995907230559